### ISSUE TITLE
Error in preparing_faces_parallel.py

### ISSUE THREAD

**Issue by shampooooo** [yuval-alaluf/stylegan3-editing#7]
'pretrained_models/shape_predictor_68_face_landmarks.dat' file exists in the path. What's the problem?

`!python prepare_data/preparing_faces_parallel.py \
--root_path /content/drive/MyDrive/Dataset/landscape \
--mode align`

1
Running on 201 paths
Here we goooo
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "prepare_data/preparing_faces_parallel.py", line 42, in extract_on_paths
    predictor = dlib.shape_predictor(SHAPE_PREDICTOR_PATH)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. dlib.shape_predictor()
    2. dlib.shape_predictor(arg0: str)

Invoked with: PosixPath('pretrained_models/shape_predictor_68_face_landmarks.dat')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "prepare_data/preparing_faces_parallel.py", line 91, in <module>
    run()
  File "/usr/local/lib/python3.7/dist-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "prepare_data/preparing_faces_parallel.py", line 85, in run
    pool.map(partial(extract_on_paths, args=args), file_chunks)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. dlib.shape_predictor()
    2. dlib.shape_predictor(arg0: str)

Invoked with: PosixPath('pretrained_models/shape_predictor_68_face_landmarks.dat')

**Comment by woctezuma** [comment]
`dlib.shape_predictor()` expects a `str`, and got a `PosixPath` instead.

**Comment by yuval-alaluf** [comment]
Thanks @woctezuma for the correction! I guess we missed this in our tests before the release. 
This has been fixed using your suggestion.
